import { useEffect, useRef, useState } from "react";
import "./styles.css";

const API = "http://127.0.0.1:8000";

export default function App() {
  const [page, setPage] = useState("image");
  const [identities, setIdentities] = useState([]);
  const [apiOnline, setApiOnline] = useState(false);
  const refresh = async () => { try { const r = await fetch(`${API}/api/identities`); if (r.ok) setIdentities(await r.json()); } catch {} };
  useEffect(() => { refresh(); fetch(`${API}/health`).then(r => setApiOnline(r.ok)).catch(() => setApiOnline(false)); }, []);
  const nav = [["webcam", "Live webcam"], ["image", "Recognize image"], ["video", "Recognize video"], ["enroll", "Enroll person"], ["people", "Manage identities"]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">FV</span><span>FaceView</span></div><p className="eyebrow">FACE RECOGNITION</p><nav>{nav.map(([id, label]) => <button key={id} className={page === id ? "nav-item active" : "nav-item"} onClick={() => setPage(id)}>{label}</button>)}</nav><div className="privacy-note">Known faces are matched against enrolled embeddings. Unmatched faces are shown as UNKNOWN.</div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">CONTROL CENTER</p><h1>{nav.find(([id]) => id === page)?.[1]}</h1></div><span className={apiOnline ? "status" : "status offline"}><i /> {apiOnline ? "API ready" : "Backend offline"}</span></header>{page === "webcam" && <LiveWebcam />}{page === "image" && <RecognizeImage />}{page === "video" && <RecognizeVideo />}{page === "enroll" && <Enroll onDone={refresh} />}{page === "people" && <People identities={identities} refresh={refresh} />}</main></div>;
}

function LiveWebcam() {
  const videoRef = useRef(null); const canvasRef = useRef(null); const streamRef = useRef(null); const timerRef = useRef(null);
  const [running, setRunning] = useState(false); const [faces, setFaces] = useState([]); const [size, setSize] = useState({ width: 1, height: 1 }); const [error, setError] = useState(""); const [lastLatency, setLastLatency] = useState(null);
  const stop = () => { clearTimeout(timerRef.current); streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; if (videoRef.current) videoRef.current.srcObject = null; setRunning(false); setFaces([]); };
  const start = async () => { setError(""); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); streamRef.current = stream; videoRef.current.srcObject = stream; await videoRef.current.play(); setSize({ width: videoRef.current.videoWidth, height: videoRef.current.videoHeight }); setRunning(true); } catch (e) { setError(e.name === "NotAllowedError" ? "Camera permission was denied. Allow camera access in the browser and try again." : `Unable to start camera: ${e.message}`); } };
  useEffect(() => () => { clearTimeout(timerRef.current); streamRef.current?.getTracks().forEach(track => track.stop()); }, []);
  useEffect(() => { if (!running) return undefined; let cancelled = false; const recognize = async () => { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas || !video.videoWidth || cancelled) { timerRef.current = setTimeout(recognize, 250); return; } canvas.width = video.videoWidth; canvas.height = video.videoHeight; canvas.getContext("2d").drawImage(video, 0, 0); const blob = await new Promise(resolve => canvas.toBlob(resolve, "image/jpeg", 0.88)); if (!blob || cancelled) return; const form = new FormData(); form.append("file", blob, "webcam-frame.jpg"); const started = performance.now(); try { const response = await fetch(`${API}/api/recognize/image`, { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw Error(data.detail || "Webcam recognition failed"); if (!cancelled) { setFaces(data.faces || []); setSize({ width: canvas.width, height: canvas.height }); setLastLatency(Math.round(performance.now() - started)); setError(""); } } catch (e) { if (!cancelled) setError(e.message); } finally { if (!cancelled) timerRef.current = setTimeout(recognize, 850); } }; recognize(); return () => { cancelled = true; clearTimeout(timerRef.current); }; }, [running]);
  const known = faces.filter(face => face.result === "KNOWN").length;
  return <Page title="Live webcam recognition" help="Allow camera access, then FaceView samples webcam frames, recognizes each detected face, and displays live labels. FaceNet runs on the backend, so recognition speed depends on your CPU."><div className="webcam-actions">{running ? <button className="danger" onClick={stop}>Stop webcam</button> : <button className="primary" onClick={start}>Start webcam</button>}<span className={running ? "camera-state active" : "camera-state"}>{running ? "Camera active" : "Camera stopped"}</span>{lastLatency !== null && <span className="camera-state">Last check: {lastLatency} ms</span>}</div>{error && <Message error>{error}</Message>}<div className="webcam-view"><video ref={videoRef} muted playsInline /><Overlay faces={faces} size={size} /></div><canvas ref={canvasRef} className="hidden-canvas" /><div className="summary"><b>{faces.length} face(s) in latest frame</b><span className="known">Known: {known}</span><span className="unknown">Unknown: {faces.length - known}</span></div></Page>;
}

function RecognizeImage() { const [file, setFile] = useState(null); const [data, setData] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const run = async () => { if (!file) return; setBusy(true); setError(""); setData(null); const form = new FormData(); form.append("file", file); try { const r = await fetch(`${API}/api/recognize/image`, { method: "POST", body: form }); const json = await r.json(); if (!r.ok) throw Error(json.detail || "Recognition failed"); setData(json); } catch (e) { setError(e.message); } finally { setBusy(false); } }; return <Page title="Image recognition" help="Upload a photo. Every detected face is boxed and classified against the database."><FileField accept="image/*" onChange={setFile} /><button className="primary" disabled={!file || busy} onClick={run}>{busy ? "Recognizing..." : "Recognize image"}</button>{error && <Message error>{error}</Message>}{data && <><ResultSummary data={data} /><ImageResult file={file} faces={data.faces || []} /></>}</Page>; }

function RecognizeVideo() { const [file, setFile] = useState(null); const [data, setData] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const run = async () => { if (!file) return; setBusy(true); setError(""); setData(null); const form = new FormData(); form.append("file", file); try { const r = await fetch(`${API}/api/recognize/video`, { method: "POST", body: form }); const json = await r.json(); if (!r.ok) throw Error(json.detail || "Video recognition failed"); setData(json); } catch (e) { setError(e.message); } finally { setBusy(false); } }; return <Page title="Video recognition" help="Upload a video. The processed video contains boxes and labels for known and unknown faces."><FileField accept="video/*" onChange={setFile} /><button className="primary" disabled={!file || busy} onClick={run}>{busy ? "Processing video..." : "Recognize video"}</button>{error && <Message error>{error}</Message>}{data && <><ResultSummary data={data} video /><video className="result-video" controls src={`${API}${data.annotated_video_url}`} /></>}</Page>; }

function Enroll({ onDone }) { const [name, setName] = useState(""); const [code, setCode] = useState(""); const [file, setFile] = useState(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const run = async () => { if (!name || !code || !file) return; setBusy(true); setMessage(""); setError(""); const form = new FormData(); form.append("file", file); try { const r = await fetch(`${API}/api/enroll/image?identity_code=${encodeURIComponent(code)}&name=${encodeURIComponent(name)}`, { method: "POST", body: form }); const json = await r.json(); if (!r.ok) throw Error(json.detail || "Enrollment failed"); setMessage(`Enrolled ${json.name} (${json.identity_code}) successfully.`); setName(""); setCode(""); setFile(null); onDone(); } catch (e) { setError(e.message); } finally { setBusy(false); } }; return <Page title="Enroll a person" help="Use a clear photo containing exactly one face. This creates an embedding; no model retraining is required."><Field label="Name" value={name} onChange={setName} placeholder="e.g. Sundar" /><Field label="Identity code" value={code} onChange={setCode} placeholder="e.g. sundar_001" /><FileField accept="image/*" onChange={setFile} /><button className="primary" disabled={!name || !code || !file || busy} onClick={run}>{busy ? "Enrolling..." : "Enroll face"}</button>{message && <Message>{message}</Message>}{error && <Message error>{error}</Message>}</Page>; }

function People({ identities, refresh }) { const [error, setError] = useState(""); const remove = async (id, name) => { if (!confirm(`Delete ${name}?`)) return; const r = await fetch(`${API}/api/identities/${id}`, { method: "DELETE" }); if (!r.ok) { const j = await r.json(); setError(j.detail || "Delete failed"); } else refresh(); }; return <Page title="Manage identities" help="Delete an identity when it should no longer be recognized.">{error && <Message error>{error}</Message>}{identities.length ? <div className="identity-list">{identities.map(x => <div className="identity" key={x.id}><div><strong>{x.name}</strong><span>{x.identity_code}</span></div><button className="danger" onClick={() => remove(x.id, x.name)}>Delete</button></div>)}</div> : <Empty>No enrolled identities yet.</Empty>}</Page>; }

function Page({ title, help, children }) { return <section className="panel page"><h2>{title}</h2><p className="help">{help}</p>{children}</section>; }
function Field({ label, value, onChange, placeholder }) { return <label className="field"><span>{label}</span><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} /></label>; }
function FileField({ accept, onChange }) { return <label className="file-field"><span>Choose file</span><input type="file" accept={accept} onChange={e => onChange(e.target.files[0] || null)} /><small>JPG, PNG, MP4 or supported browser video</small></label>; }
function Message({ children, error }) { return <div className={error ? "message error" : "message"}>{children}</div>; }
function Empty({ children }) { return <div className="empty">{children}</div>; }
function ResultSummary({ data, video }) { return <div className="summary"><b>{video ? `${data.frames_processed || 0} frames processed` : `${data.face_count || 0} face(s) detected`}</b><span className="known">Known: {video ? data.known_faces : (data.faces || []).filter(x => x.result === "KNOWN").length}</span><span className="unknown">Unknown: {video ? data.unknown_faces : (data.faces || []).filter(x => x.result !== "KNOWN").length}</span></div>; }
function ImageResult({ file, faces }) { const [size, setSize] = useState({ width: 1, height: 1 }); return <div className="image-result"><img src={URL.createObjectURL(file)} onLoad={e => setSize({ width: e.currentTarget.naturalWidth, height: e.currentTarget.naturalHeight })} /><Overlay faces={faces} size={size} /></div>; }
function Overlay({ faces, size }) { return <div className="overlay">{faces.map((f, i) => { const [x, y, width, height] = f.bbox; return <div key={i} className={f.result === "KNOWN" ? "box known-box" : "box unknown-box"} style={{ left: `${x / size.width * 100}%`, top: `${y / size.height * 100}%`, width: `${width / size.width * 100}%`, height: `${height / size.height * 100}%` }}><span>{f.result === "KNOWN" ? `${f.name} | ID: ${f.identity_id}` : "UNKNOWN"}</span></div>; })}</div>; }
